id: A29354D99
title: The Prayer which is the Source of All True Realization
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.811204
  last_modified_at: 2022-03-01 00:58:13.811207
