id: A29354D99
title: Prayer to Tārā, Combined with Her Mantra
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.780163
  last_modified_at: 2022-03-01 00:58:13.780166
