id: A29354D99
title: Concise Tsok Feast
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.741098
  last_modified_at: 2022-03-01 00:58:13.741100
