id: A29354D99
title: 'The Glorious Gift of Longevity and Granting All Desires: A Liturgy for Saving
  Lives'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.801166
  last_modified_at: 2022-03-01 00:58:13.801169
