id: A29354D99
title: Brief Offering Prayer to the Oath-Bound Vajrasādhu
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.735978
  last_modified_at: 2022-03-01 00:58:13.735981
