id: A29354D99
title: Wrathful Guru Mantra Visualization
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.843776
  last_modified_at: 2022-03-01 00:58:13.843779
