id: A29354D99
title: 'Beautiful Adornment of the Earth: In Praise of Kṣitigarbha'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.727341
  last_modified_at: 2022-03-01 00:58:13.727344
