id: A29354D99
title: A Brief Version of the 'Chinese' Practice of Averting Periodic Obstacles
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.714435
  last_modified_at: 2022-03-01 00:58:13.714440
