id: A29354D99
title: 'Swift Infusion of Blessings: A Guru Yoga based on Jamgön Mipham Gyatso'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.799198
  last_modified_at: 2022-03-01 00:58:13.799201
