id: A29354D99
title: 'Snowy Lands: Praises to the Great Dharma Emperor Tri Songdetsen'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.795230
  last_modified_at: 2022-03-01 00:58:13.795234
