id: A29354D99
title: The Swift Fulfilment of All Wishes—Offering the Flag of Windhorse
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.818249
  last_modified_at: 2022-03-01 00:58:13.818251
