id: A29354D99
title: Great Clouds of First-Portion Offerings for Prosperity
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.751283
  last_modified_at: 2022-03-01 00:58:13.751286
