id: A29354D99
title: Brief Windhorse Invocation
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.739750
  last_modified_at: 2022-03-01 00:58:13.739753
