id: A29354D99
title: Prayer to Akṣobhya
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.772000
  last_modified_at: 2022-03-01 00:58:13.772003
