id: A29354D99
title: Kṣitigarbha Visualization and Mantra Recitation
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.761753
  last_modified_at: 2022-03-01 00:58:13.761756
