id: A29354D99
title: A Brief Prayer for the Spontaneous Fulfilment of Aspirations
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.713061
  last_modified_at: 2022-03-01 00:58:13.713065
