id: A29354D99
title: 'The Spontaneous Fulfilment of Wishes: A Daily Prayer to Gesar, King of the
  Dralas'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.814475
  last_modified_at: 2022-03-01 00:58:13.814478
