id: A29354D99
title: Offering to the Five Medicine Sisters, Guardians of the Earth
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.764067
  last_modified_at: 2022-03-01 00:58:13.764069
