id: A29354D99
title: Brief Offering Prayer to Ekajaṭī
type: translation
source_metadata:
  languages:
  - en
  - es
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.732102
  last_modified_at: 2022-03-01 00:58:13.732105
