id: A29354D99
title: Three Prayers from the Earth Pig Year
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.830490
  last_modified_at: 2022-03-01 00:58:13.830493
