id: A29354D99
title: In Praise of the Protector Mañjughoṣa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.760707
  last_modified_at: 2022-03-01 00:58:13.760709
