id: A29354D99
title: Visualization and Recitation of the Six-Syllable Mantra of Avalokiteśvara
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.836259
  last_modified_at: 2022-03-01 00:58:13.836261
