id: A29354D99
title: Prayer Recalling the Life and Liberation of the Mañjunātha Guru
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.769551
  last_modified_at: 2022-03-01 00:58:13.769554
