id: A29354D99
title: A Brief Prayer for Summoning Prosperity
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.710857
  last_modified_at: 2022-03-01 00:58:13.710864
