id: A29354D99
title: 'Gentle Splendour: Praises to the Great Abbot Śāntarakṣita'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.748714
  last_modified_at: 2022-03-01 00:58:13.748717
