id: A29354D99
title: Prayer to the Sovereign of Dharma and Retinue
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.781446
  last_modified_at: 2022-03-01 00:58:13.781449
