id: A29354D99
title: 'A Shower of Blessings: A Guru Yoga Practice to Accompany the Seven-Line Prayer'
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.719040
  last_modified_at: 2022-03-01 00:58:13.719043
