id: A29354D99
title: 'The Three Kāyas: Praises to the Great Master Padmasambhava'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.824443
  last_modified_at: 2022-03-01 00:58:13.824445
