id: A29354D99
title: 'Excellent Vase of Splendour: The Tsok Feast Offering to Accompany the Vajra
  Seven-Line Prayer'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.743371
  last_modified_at: 2022-03-01 00:58:13.743374
