id: A29354D99
title: 'Words to Delight the Sovereigns of the Dharma: A Prayer of Aspiration for
  the Flourishing and Spread of the Ancient Translation Tradition'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.842087
  last_modified_at: 2022-03-01 00:58:13.842091
