id: A29354D99
title: The Prayer and Offering to 'The Great Lion, Gesar the Jewel', that Spontaneously
  Accomplishes Activities
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.808804
  last_modified_at: 2022-03-01 00:58:13.808807
