id: A29354D99
title: 'In Praise of Mañjuśrī: Increasing Intelligence to the Full'
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.758226
  last_modified_at: 2022-03-01 00:58:13.758229
