id: A29354D99
title: Guru Yoga Focusing upon Noble KurukullÄ
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.753686
  last_modified_at: 2022-03-01 00:58:13.753689
