id: A29354D99
title: The Swift Accomplishment of Enlightened Activity through Invocation and Offering
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.815740
  last_modified_at: 2022-03-01 00:58:13.815743
