id: A29354D99
title: 'Shower of Blessings: A Guru Yoga of the Great Paṇḍita, Glorious Rongzom'
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.792620
  last_modified_at: 2022-03-01 00:58:13.792623
