id: A29354D99
title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.828032
  last_modified_at: 2022-03-01 00:58:13.828036
