id: A29354D99
title: 'Great Treasury of Siddhis: A Guru Yoga of Paṇchen Smṛti'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.752502
  last_modified_at: 2022-03-01 00:58:13.752504
