id: A29354D99
title: Short Sang Offering to KurukullÄ
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.789450
  last_modified_at: 2022-03-01 00:58:13.789452
