id: A29354D99
title: Sukhāvatī Aspiration
type: translation
source_metadata:
  languages:
  - en
  - pt
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.797221
  last_modified_at: 2022-03-01 00:58:13.797224
