id: A29354D99
title: Brief Dzogchen Lineage Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.728443
  last_modified_at: 2022-03-01 00:58:13.728446
