id: A29354D99
title: 'Illuminating the Path to Liberation: A Preliminary Practice (Ngöndro)'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:58:13.755284
  last_modified_at: 2022-03-01 00:58:13.755287
